### ISSUE TITLE
Invalid PSR-4 class warning

### ISSUE THREAD

**Issue by CrystalShardz** [CrystalShardz/parakeet#2]
When installing after cloning repository, the following warning was displayed within Composer:

```
Class App\Exceptions\HostNotSetException located in ./app/Exceptions/HostNetSetException.php does not comply with psr-4 autoloading standard. Skipping.
```

**Comment by rmhassan** [comment]
According to this answer
https://stackoverflow.com/questions/65038599/class-does-not-comply-with-psr-4-autoloading-standard-skipping
Everything seems fine. 
What might be changed for this to work?

**Comment by CrystalShardz** [comment]
This would just need the file name changing as it has been named incorrectly. (my poor typing skills strike again!)
